[package]
name = "devsparkle/overture"
description = "Source code management engine for Roblox"
version = "2.2.4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
