[package]
name = "unnamedcorp/overture"
description = "Source code management engine for Roblox"
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
